app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb

Added alerts in partial _flashes and rendered them in application.html.erb

added alerts

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
db/migrate/20181126172848_add_first_name_to_users.rb
db/migrate/20181126172916_add_last_name_to_users.rb
db/schema.rb

added user first name and last name + authenticate restrictions

added user first name and last name + authenticate restrictions

---

app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb

updated forms and added user validations on first name and last name

---

app/controllers/bookings_controller.rb
app/views/bookings/index.html.erb
app/views/bookings/show.html.erb
db/seeds.rb

added basic info to show view and set_booking to bookings controller

Add info to bookings show

---

app/models/user.rb

added has_many :games, :bookings to user model

Has many to user

---

app/controllers/games_controller.rb
app/views/shared/_form.html.erb
db/seeds.rb

Created instance of time control in seed
Added f.association in simple form for new game
Modified create action in games controller

fixed new game form

---

app/views/games/index.html.erb
db/schema.rb
db/seeds.rb

added sample image url to seeds.rb

added image to seeds

---

app/controllers/application_controller.rb
app/controllers/games_controller.rb
app/policies/game_policy.rb
app/views/games/show.html.erb

added pundit authorisations and added edit bouton on games created by user

pundit authorisations

---

app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/unlocks/new.html.erb
app/views/games/new.html.erb

Registration/session/pw/etc and games#new centered

Devise forms centering

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_footer.scss
app/controllers/games_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/models/game.rb
app/views/games/index.html.erb
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
config/initializers/geocoder.rb
db/migrate/20181128093355_add_coordinates_to_games.rb
db/schema.rb
db/seeds.rb
package.json
yarn.lock

map display

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_list.scss
app/views/bookings/index.html.erb
app/views/games/list.erb

when user has no hosted games, bouton with host a game
when user has no bookings, bouton with find open games

added buttons to my games and my bookings

---

app/assets/stylesheets/layouts/_index.scss
app/assets/stylesheets/layouts/_map.scss
app/assets/stylesheets/layouts/_utilities.scss
app/assets/stylesheets/pages/_game.scss
app/views/games/show.html.erb

@jcfabre good pour toi? le footer ne bouge plus et on peut scroller sur les cards dans "/games"

footer sticky and body do not scroll anymor

---

app/models/user.rb
db/migrate/20181129101239_add_rating_to_users.rb
db/schema.rb
db/seeds.rb

added a rating field to user database
updated seed as well

added rating to user

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/layouts/_map.scss
app/views/games/index.html.erb

modified game cards in games index to focus on avatar and level and time control

Game cards

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/layouts/_map.scss
app/assets/stylesheets/layouts/_utilities.scss
app/controllers/games_controller.rb
app/javascript/plugins/init_mapbox.js
app/views/bookings/index.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/games/index.html.erb
app/views/games/list.erb
app/views/shared/_infowindow.html.erb
app/views/users/show.html.erb

footer fixed

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_message.scss
app/views/shared/_infowindow.html.erb
app/views/users/show.html.erb
db/schema.rb

Profile page for users show

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_card.scss
app/views/games/index.html.erb
app/views/games/list.erb
app/views/shared/_form.html.erb
app/views/shared/_games_cards.html.erb

* game cards
* remove time flexible to new game form

modified game cards

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_message.scss
app/assets/stylesheets/components/_style_gnr.scss
app/policies/user_policy.rb
app/views/users/edit.html.erb
app/views/users/show.html.erb

fixed the avatar padding and edit_users_path link

---

app/assets/stylesheets/components/_navbar.scss
app/helpers/application_helper.rb
app/views/shared/_navbar.html.erb

To solve later : show current navigation in dropdown

nav links dropdown + nav current page UX + default pic avatar

---

app/assets/stylesheets/components/_banner.scss
app/views/bookings/show.html.erb
app/views/reviews/new.html.erb

fixed booking pages and add review form center

add a review form and show booking page
